package entidades;
// Generated 27-feb-2013 12:31:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable {


     private int idarticulos;
     private String codigo;
     private String descripcion;
     private Double precio;
     private Double precioIva;
     private String usuarioMod;
     private Date fechaMod;
     private Integer idfamilias;

    public Articulos() {
    }

	
    public Articulos(int idarticulos) {
        this.idarticulos = idarticulos;
    }
    public Articulos(int idarticulos, String codigo, String descripcion, Double precio, Double precioIva, String usuarioMod, Date fechaMod, Integer idfamilias) {
       this.idarticulos = idarticulos;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.precio = precio;
       this.precioIva = precioIva;
       this.usuarioMod = usuarioMod;
       this.fechaMod = fechaMod;
       this.idfamilias = idfamilias;
    }
   
    public int getIdarticulos() {
        return this.idarticulos;
    }
    
    public void setIdarticulos(int idarticulos) {
        this.idarticulos = idarticulos;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Double getPrecioIva() {
        return this.precioIva;
    }
    
    public void setPrecioIva(Double precioIva) {
        this.precioIva = precioIva;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }
    public Integer getIdfamilias() {
        return this.idfamilias;
    }
    
    public void setIdfamilias(Integer idfamilias) {
        this.idfamilias = idfamilias;
    }




}


