package entidades;
// Generated 23-ene-2013 12:35:51 by Hibernate Tools 3.2.1.GA



/**
 * Contadores generated by hbm2java
 */
public class Contadores  implements java.io.Serializable {


     private int idcontadores;
     private String tabla;
     private Integer valor;

    public Contadores() {
    }

	
    public Contadores(int idcontadores) {
        this.idcontadores = idcontadores;
    }
    public Contadores(int idcontadores, String tabla, Integer valor) {
       this.idcontadores = idcontadores;
       this.tabla = tabla;
       this.valor = valor;
    }
   
    public int getIdcontadores() {
        return this.idcontadores;
    }
    
    public void setIdcontadores(int idcontadores) {
        this.idcontadores = idcontadores;
    }
    public String getTabla() {
        return this.tabla;
    }
    
    public void setTabla(String tabla) {
        this.tabla = tabla;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }




}


