package entidades;
// Generated 27-feb-2013 12:31:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Familias generated by hbm2java
 */
public class Familias  implements java.io.Serializable {


     private int idfamilias;
     private String codigo;
     private String descripcion;
     private String usuarioMod;
     private Date fechaMod;

    public Familias() {
    }

	
    public Familias(int idfamilias) {
        this.idfamilias = idfamilias;
    }
    public Familias(int idfamilias, String codigo, String descripcion, String usuarioMod, Date fechaMod) {
       this.idfamilias = idfamilias;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.usuarioMod = usuarioMod;
       this.fechaMod = fechaMod;
    }
   
    public int getIdfamilias() {
        return this.idfamilias;
    }
    
    public void setIdfamilias(int idfamilias) {
        this.idfamilias = idfamilias;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


