package entidades;
// Generated 27-feb-2013 12:31:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Lineasticket generated by hbm2java
 */
public class Lineasticket  implements java.io.Serializable {


     private int idTicket;
     private String numeroTicket;
     private String codigoEmpleado;
     private String concepto;
     private Integer cantidad;
     private Double precio;
     private Double iva;
     private Date fechaMod;
     private String usuarioMod;
     private Integer descuento;
     private Double importe;
     private Double importeConIva;

    public Lineasticket() {
    }

	
    public Lineasticket(int idTicket) {
        this.idTicket = idTicket;
    }
    public Lineasticket(int idTicket, String numeroTicket, String codigoEmpleado, String concepto, Integer cantidad, Double precio, Double iva, Date fechaMod, String usuarioMod, Integer descuento, Double importe, Double importeConIva) {
       this.idTicket = idTicket;
       this.numeroTicket = numeroTicket;
       this.codigoEmpleado = codigoEmpleado;
       this.concepto = concepto;
       this.cantidad = cantidad;
       this.precio = precio;
       this.iva = iva;
       this.fechaMod = fechaMod;
       this.usuarioMod = usuarioMod;
       this.descuento = descuento;
       this.importe = importe;
       this.importeConIva = importeConIva;
    }
   
    public int getIdTicket() {
        return this.idTicket;
    }
    
    public void setIdTicket(int idTicket) {
        this.idTicket = idTicket;
    }
    public String getNumeroTicket() {
        return this.numeroTicket;
    }
    
    public void setNumeroTicket(String numeroTicket) {
        this.numeroTicket = numeroTicket;
    }
    public String getCodigoEmpleado() {
        return this.codigoEmpleado;
    }
    
    public void setCodigoEmpleado(String codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Double getIva() {
        return this.iva;
    }
    
    public void setIva(Double iva) {
        this.iva = iva;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public Integer getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Integer descuento) {
        this.descuento = descuento;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }
    public Double getImporteConIva() {
        return this.importeConIva;
    }
    
    public void setImporteConIva(Double importeConIva) {
        this.importeConIva = importeConIva;
    }




}


