/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidades.Familias;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mgacosta
 */
public class frmFamilias extends javax.swing.JFrame {
     String accion="Nuevo";
     int Id_Actualizar;
    private DefaultTableModel modelo;
    /**
     * Creates new form frmFamilias
     */
    public frmFamilias() {
        initComponents();
        setLocationRelativeTo(null);
        CargarFamilias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnuEditar = new javax.swing.JMenuItem();
        mnuEliminar = new javax.swing.JMenuItem();
        mnuAddArticulos = new javax.swing.JMenuItem();
        txtCodigo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        cmdNuevo = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblfamilias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        mnuEditar.setText("Editar");
        mnuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuEditar);

        mnuEliminar.setText("Eliminar");
        mnuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuEliminar);

        mnuAddArticulos.setText("Añadir Articulos");
        mnuAddArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddArticulosActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuAddArticulos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cmdNuevo.setIcon(new javax.swing.ImageIcon("D:\\descargas\\1359557344_asterisk_yellow.png")); // NOI18N
        cmdNuevo.setText("Nuevo");
        cmdNuevo.setToolTipText("");
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });

        cmdGuardar.setIcon(new javax.swing.ImageIcon("D:\\descargas\\1359557227_document-save-as.png")); // NOI18N
        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        cmdEliminar.setIcon(new javax.swing.ImageIcon("D:\\descargas\\1359557381_DeleteRed.png")); // NOI18N
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });

        cmdSalir.setIcon(new javax.swing.ImageIcon("D:\\descargas\\1359557429_Exit.png")); // NOI18N
        cmdSalir.setText("Cerrar");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });

        tblfamilias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblfamilias.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tblfamilias);

        jLabel1.setText("Codigo");

        jLabel2.setText("Descripcion");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Familias");

        jLabel4.setText("Este formulacio es para .........");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(jLabel4))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(jLabel1))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(txtCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(txtDescripcion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(0, 0, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cmdNuevo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cmdGuardar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cmdEliminar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(51, 51, 51)
                        .add(cmdSalir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtDescripcion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cmdSalir)
                    .add(cmdEliminar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmdGuardar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(cmdNuevo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 void CargarFamilias(){
   
    String[] titulos = {"ID","Codigo","Descripcion"};
    String[] registro = new String[3];
    modelo= new DefaultTableModel(null,titulos);
    
    BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
    List LisataFamilias= Operaciones.ObtenerFamilias();
   
    Iterator iter = LisataFamilias.iterator();
    while (iter.hasNext())
    {
      Familias familias = (Familias) iter.next();    
      registro[0]=String.valueOf(familias.getIdfamilias());
      registro[1]=familias.getCodigo();
      registro[2]=familias.getDescripcion();
      modelo.addRow(registro);
    }
    tblfamilias.setModel(modelo);
}  
 void BuscarFamiliasID(String vID){
  
  BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
    List LisataFamilias= Operaciones.ObtenerFamiliasID(vID);
   
    Iterator iter = LisataFamilias.iterator();
    while (iter.hasNext())
    {
      Familias familias = (Familias) iter.next(); 
      txtCodigo.setText(familias.getCodigo());
      txtDescripcion.setText(familias.getDescripcion());
      Id_Actualizar=familias.getIdfamilias();
    }
       
  
}

    
    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
        // TODO add your handling code here:
        txtCodigo.setText("");
        txtDescripcion.setText("");
        accion="Nuevo";
    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        // TODO add your handling code here:
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
        if (accion.equals("Nuevo")){
            Operaciones.InsertarFamilia(txtCodigo.getText(), txtDescripcion.getText()); 
        }
        else{
            Operaciones.ActualizarFamilia(Id_Actualizar,txtCodigo.getText(), txtDescripcion.getText());  
        }   
        CargarFamilias();
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void mnuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarActionPerformed
              
        int filaSele;
        String ID;
        try{
            
           filaSele=this.tblfamilias.getSelectedRow(); 
           if (filaSele==-1){
               JOptionPane.showMessageDialog(this, "Seleccione una fila ", "Grid", JOptionPane.INFORMATION_MESSAGE);
           }
           else{
               accion="modificar";
               modelo= (DefaultTableModel) this.tblfamilias.getModel();
               ID = (String) modelo.getValueAt(filaSele, 0);
               //habilitar();
               BuscarFamiliasID(ID);
              // habilitar();
           }        
        }
          catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString(), "Grid", JOptionPane.INFORMATION_MESSAGE);
        }
            
    }//GEN-LAST:event_mnuEditarActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        // TODO add your handling code here:
        
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
        try{
                                   
        int Res= JOptionPane.showConfirmDialog(new JFrame(),"Eliminar la familia ?", 
                                                "Eliminar",JOptionPane.YES_NO_OPTION) ;
              if (Res== JOptionPane.YES_OPTION){
                      accion="borrar";
                      Operaciones.BorrarFamilia(Id_Actualizar);
                      Operaciones.BorrarArticulosFamilia(Id_Actualizar);
                      CargarFamilias();   
                      txtCodigo.setText("");
                      txtDescripcion.setText("");
                      Id_Actualizar=-1;
            }
        }
          catch (Exception e) {
            JOptionPane.showMessageDialog(this,  e.toString(), "Borrar", 
                                            JOptionPane.INFORMATION_MESSAGE);   
        }
         
         
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void mnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarActionPerformed
        // TODO add your handling code here:
         BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
         int filaSele;  Integer ID;
        try{
           filaSele=this.tblfamilias.getSelectedRow(); 
           if (filaSele==-1){
               JOptionPane.showMessageDialog(this, "Seleccione una fila ", "Grid", 
                       JOptionPane.INFORMATION_MESSAGE);
           }
           else{
              int Res= JOptionPane.showConfirmDialog(new JFrame(),
                      "Eliminar la familia ?", "Eliminar",JOptionPane.YES_NO_OPTION) ;
              if (Res== JOptionPane.YES_OPTION){
                      accion="borrar";
                      modelo= (DefaultTableModel) this.tblfamilias.getModel();
                      String SID=(String)modelo.getValueAt(filaSele, 0);
                     
                      ID =Integer.parseInt (SID);

                      Operaciones.BorrarFamilia(ID);
                      Operaciones.BorrarArticulosFamilia(ID);
                      CargarFamilias();   
                      txtCodigo.setText("");
                      txtDescripcion.setText("");
                      Id_Actualizar=-1;
              }
         }
        }
          catch (Exception e){
            JOptionPane.showMessageDialog(this,  e, "Borrar", JOptionPane.INFORMATION_MESSAGE);   
        }
         
         
         
         
    }//GEN-LAST:event_mnuEliminarActionPerformed

    private void mnuAddArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddArticulosActionPerformed
        // TODO add your handling code here:
              
         int filaSele;  Integer ID;
        
         try{
           filaSele=this.tblfamilias.getSelectedRow(); 
           if (filaSele==-1){
               JOptionPane.showMessageDialog(this, "Seleccione una fila ", "Grid", 
                       JOptionPane.INFORMATION_MESSAGE);
           }
           else{
             
              modelo= (DefaultTableModel) this.tblfamilias.getModel();
              String SID=(String)modelo.getValueAt(filaSele, 0);
              String Familia=(String)modelo.getValueAt(filaSele, 2);
              ID =Integer.parseInt (SID);
              frmArticulos f= new frmArticulos(ID,Familia);
             f.setVisible(true);    
         }
        }
          catch (Exception e){
            JOptionPane.showMessageDialog(this,  e, "Borrar", JOptionPane.INFORMATION_MESSAGE);   
        }
        
        
        
        
        
        
        
        
       
         

    }//GEN-LAST:event_mnuAddArticulosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFamilias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFamilias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFamilias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFamilias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFamilias().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuAddArticulos;
    private javax.swing.JMenuItem mnuEditar;
    private javax.swing.JMenuItem mnuEliminar;
    private javax.swing.JTable tblfamilias;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
