/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidades.Articulos;
import entidades.Familias;
import entidades.Lineasticket;
import entidades.Tickets;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import utilidades.ManejadorFechas;

/**
 *
 * @author mgacosta
 */
public class tpvTactil extends javax.swing.JFrame {

    /**
     * Creates new form tpvTactil
     */
    private int Ultima=0;
    private String NumeroTicket="";
    
    public tpvTactil() {
        initComponents();
        setLocationRelativeTo(null);
        BorrarTextoBotones(jPanel1);
        BorrarTextoBotones(jPanel2);
        Ultima= CargarFamilias(Ultima);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdFamilia1 = new javax.swing.JButton();
        cmdFamilia2 = new javax.swing.JButton();
        cmdFamilia3 = new javax.swing.JButton();
        cmdFamilia4 = new javax.swing.JButton();
        cmdFamilia5 = new javax.swing.JButton();
        cmdFamilia6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmdArticulo01 = new javax.swing.JButton();
        cmdArticulo02 = new javax.swing.JButton();
        cmdArticulo03 = new javax.swing.JButton();
        cmdArticulo04 = new javax.swing.JButton();
        cmdArticulo05 = new javax.swing.JButton();
        cmdArticulo06 = new javax.swing.JButton();
        cmdArticulo07 = new javax.swing.JButton();
        cmdArticulo08 = new javax.swing.JButton();
        cmdArticulo09 = new javax.swing.JButton();
        cmdArticulo10 = new javax.swing.JButton();
        cmdArticulo11 = new javax.swing.JButton();
        cmdArticulo12 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmdNuevo = new javax.swing.JButton();
        cmdBorrarLinea = new javax.swing.JButton();
        cmdCodigoBarras = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        txtDisplay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 2, 2));

        cmdFamilia1.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia1.setName("familia1"); // NOI18N
        cmdFamilia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia1);

        cmdFamilia2.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia2.setName("familia2"); // NOI18N
        cmdFamilia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia2ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia2);

        cmdFamilia3.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia3.setName("familia4"); // NOI18N
        cmdFamilia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia3ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia3);

        cmdFamilia4.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia4.setName("familia5"); // NOI18N
        cmdFamilia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia4ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia4);

        cmdFamilia5.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia5.setName("familia3"); // NOI18N
        cmdFamilia5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia5ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia5);

        cmdFamilia6.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia6.setName("familia6"); // NOI18N
        cmdFamilia6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia6ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia6);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new java.awt.GridLayout(3, 6, 2, 2));

        cmdArticulo01.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo01.setName("articulos1"); // NOI18N
        cmdArticulo01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo01ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo01);

        cmdArticulo02.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo02.setName("articulos2"); // NOI18N
        cmdArticulo02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo02ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo02);

        cmdArticulo03.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo03.setName("articulos3"); // NOI18N
        cmdArticulo03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo03ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo03);

        cmdArticulo04.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo04.setName("articulos4"); // NOI18N
        cmdArticulo04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo04ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo04);

        cmdArticulo05.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo05.setName("articulos5"); // NOI18N
        cmdArticulo05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo05ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo05);

        cmdArticulo06.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo06.setName("articulos6"); // NOI18N
        cmdArticulo06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo06ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo06);

        cmdArticulo07.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo07.setName("articulos7"); // NOI18N
        cmdArticulo07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo07ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo07);

        cmdArticulo08.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo08.setName("articulos8"); // NOI18N
        cmdArticulo08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo08ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo08);

        cmdArticulo09.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo09.setName("articulos9"); // NOI18N
        cmdArticulo09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo09ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo09);

        cmdArticulo10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo10.setName("articulos10"); // NOI18N
        cmdArticulo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo10ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo10);

        cmdArticulo11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo11.setName("articulos11"); // NOI18N
        cmdArticulo11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo11ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo11);

        cmdArticulo12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdArticulo12.setName("articulos12"); // NOI18N
        cmdArticulo12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArticulo12ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdArticulo12);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText(">>");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(new java.awt.GridLayout(8, 1));

        cmdNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdNuevo.setText("Nuevo Ticket");
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdNuevo);

        cmdBorrarLinea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdBorrarLinea.setText("Borrar Linea");
        cmdBorrarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarLineaActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrarLinea);

        cmdCodigoBarras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdCodigoBarras.setText("Codigo de Barras");
        cmdCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCodigoBarrasActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCodigoBarras);

        cmdSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSalir);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText(">>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("<<");
        jPanel3.add(jButton3);

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton23.setText(">>");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));
        jPanel4.setLayout(new java.awt.GridLayout(4, 3, 2, 2));

        jButton24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton24.setText("1");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton24);

        jButton28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton28.setText("2");
        jPanel4.add(jButton28);

        jButton32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton32.setText("3");
        jPanel4.add(jButton32);

        jButton30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton30.setText("4");
        jPanel4.add(jButton30);

        jButton25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton25.setText("5");
        jPanel4.add(jButton25);

        jButton31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton31.setText("6");
        jPanel4.add(jButton31);

        jButton35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton35.setText("7");
        jPanel4.add(jButton35);

        jButton34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton34.setText("8");
        jPanel4.add(jButton34);

        jButton33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton33.setText("9");
        jPanel4.add(jButton33);

        jButton29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton29.setText("0");
        jPanel4.add(jButton29);

        jButton26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton26.setText(".");
        jPanel4.add(jButton26);

        jButton27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton27.setText("Del");
        jPanel4.add(jButton27);

        txtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDisplay))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        Articulos ObtenerPrecioArticuloPorCodigo(String Codigo){
       
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
        Articulos A;
        List ListaArticulos= Operaciones.ObtenerArticulos();
        for (int i=0;i<ListaArticulos.size();i++){
            A=(Articulos) ListaArticulos.get(i);
            if (A.getDescripcion().equals(Codigo)){
                return A;
            }
                    
        }
        return null;
        
       
    }
    
    Familias ObtenerIdFamiliaPorCodigo(String Codigo){
       
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
        Familias F;
        List ListaFamilias= Operaciones.ObtenerFamilias();
        for (int i=0;i<ListaFamilias.size();i++){
            F=(Familias) ListaFamilias.get(i);
            if (F.getCodigo().equals(Codigo)){
                return F;
            }
                    
        }
        return null;
        
       
    }
            
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        BorrarTextoBotones(jPanel1);
       Ultima= CargarFamilias(Ultima);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton24ActionPerformed

    private void cmdFamilia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia2ActionPerformed
        // TODO add your handling code here:
         BorrarTextoBotones(jPanel2);
         BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
          Familias F;
          F=Operaciones.ObtenerIdFamiliaPorCodigo(cmdFamilia2.getText());
           CargarArticulos(0,String.valueOf(F.getIdfamilias()));
        // txtDisplay.setText(String.valueOf(F.getIdfamilias()));
    }//GEN-LAST:event_cmdFamilia2ActionPerformed

    private void cmdFamilia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia1ActionPerformed
        // TODO add your handling code here:
         BorrarTextoBotones(jPanel2);
     //     BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
          Familias F;
         // F=Operaciones.ObtenerIdFamiliaPorCodigo(jButton1.getText());
         F=ObtenerIdFamiliaPorCodigo(cmdFamilia1.getText());
         CargarArticulos(0,String.valueOf(F.getIdfamilias()));
              

    }//GEN-LAST:event_cmdFamilia1ActionPerformed

    private void cmdFamilia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia3ActionPerformed
        // TODO add your handling code here:
         BorrarTextoBotones(jPanel2);
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
              Familias F;
              F=Operaciones.ObtenerIdFamiliaPorCodigo(cmdFamilia3.getText());
             
             CargarArticulos(0,String.valueOf(F.getIdfamilias()));
    }//GEN-LAST:event_cmdFamilia3ActionPerformed

    private void cmdFamilia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia4ActionPerformed
        // TODO add your handling code here:
         BorrarTextoBotones(jPanel2);
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
              Familias F;
              F=Operaciones.ObtenerIdFamiliaPorCodigo(cmdFamilia4.getText());
             
             CargarArticulos(0,String.valueOf(F.getIdfamilias()));
    }//GEN-LAST:event_cmdFamilia4ActionPerformed

    private void cmdFamilia5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia5ActionPerformed
        // TODO add your handling code here:
         BorrarTextoBotones(jPanel2);
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
              Familias F;
              F=Operaciones.ObtenerIdFamiliaPorCodigo(cmdFamilia5.getText());
             
             CargarArticulos(0,String.valueOf(F.getIdfamilias()));
    }//GEN-LAST:event_cmdFamilia5ActionPerformed

    private void cmdFamilia6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia6ActionPerformed
        // TODO add your handling code here
         BorrarTextoBotones(jPanel2);
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
              Familias F;
              F=Operaciones.ObtenerIdFamiliaPorCodigo(cmdFamilia6.getText());
             
             CargarArticulos(0,String.valueOf(F.getIdfamilias()));
    }//GEN-LAST:event_cmdFamilia6ActionPerformed


    private void cmdArticulo01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo01ActionPerformed
        // TODO add your handling code here:
        
        ManejadorFechas FechaActual=new ManejadorFechas();
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo01.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo01.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
              
       
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
        if (NumeroTicket.length()==0){ 
            String fecha=FechaActual.getFechaActual();         
            NumeroTicket=Operaciones.ObtenerNumeroTicket();
            Operaciones.InsertarTickets(new Date(), 0, 0);
        }
        
        
        
             
        
        int Cantidad= Integer.parseInt((txtDisplay.getText().toString()));
              
        Operaciones.InsertarLineaTickets(NumeroTicket,cmdArticulo01.getText(),
                   Cantidad,A.getPrecio(),A.getPrecio()*Cantidad,0,0,0);
          
         
        
        
    
    }//GEN-LAST:event_cmdArticulo01ActionPerformed

    private void cmdArticulo02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo02ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo02.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo02.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo02ActionPerformed

    private void cmdArticulo03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo03ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo03.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo03.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo03ActionPerformed

    private void cmdArticulo04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo04ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo04.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo04.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo04ActionPerformed

    private void cmdArticulo05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo05ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo05.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo05.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo05ActionPerformed

    private void cmdArticulo06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo06ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo06.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo06.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo06ActionPerformed

    private void cmdArticulo07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo07ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo07.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo07.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo07ActionPerformed

    private void cmdArticulo08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo08ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo08.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo08.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo08ActionPerformed

    private void cmdArticulo09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo09ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo09.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo09.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo09ActionPerformed

    private void cmdArticulo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo10ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo10.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo10.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo10ActionPerformed

    private void cmdArticulo11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo11ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo11.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo11.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo11ActionPerformed

    private void cmdArticulo12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArticulo12ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(cmdArticulo12.getText());
        Object nuevo[]= {txtDisplay.getText(),cmdArticulo12.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_cmdArticulo12ActionPerformed

    private void cmdBorrarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarLineaActionPerformed
        // TODO add your handling code here:
        int filaSele;
        try{
           filaSele=this.jTable1.getSelectedRow(); 
           if (filaSele==-1){
               JOptionPane.showMessageDialog(this, "Seleccione una fila ", "Grid",
                       JOptionPane.INFORMATION_MESSAGE);
           }
           else{
               BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
              ((DefaultTableModel) jTable1.getModel()).removeRow(filaSele);
               Operaciones.BorrarLineaTickets(Operaciones.ObtenerIdLineaTicketPorNumero("33",1).getIdTicket());
           }        
        }
          catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString(), "Grid", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_cmdBorrarLineaActionPerformed

    private void cmdCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCodigoBarrasActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        
        frmCodigoBarras f = new frmCodigoBarras(this,this.jTable1);
        f.setVisible(true);
    }//GEN-LAST:event_cmdCodigoBarrasActionPerformed

    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
        // TODO add your handling code here:
        
        NumeroTicket="";
        
//      entidades.Contadores Contador=  ObtenerContador("Familias");
//  
//          if (Contador.getValor()==0){
//              InsertarContador("Familias",1);
//          }
//          else{ 
//              ActualizarContador(Contador.getIdcontadores(),"Familias",Contador.getValor()+1);
//          } 
      
          
//        } catch (ParseException ex) {
//            Logger.getLogger(tpvTactil.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jButton2ActionPerformed
 
 int CargarArticulos(int PosInicial,String IdFamilia){
    int IndiceBotones=0;
    int i;
    Component[] componentes =jPanel2.getComponents();
    BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
    List ListaArticulos;
    ListaArticulos= Operaciones.ObtenerArticulosFamilia(IdFamilia);
    if (PosInicial==ListaArticulos.size()) PosInicial=0;
      for  ( i=PosInicial;i<ListaArticulos.size();i++){
         Articulos articulo=  (Articulos) ListaArticulos.get(i);
         JButton Boton;
         Boton= BotonPorNombre ("articulos"+(IndiceBotones+1),jPanel2);
         Boton.setText(articulo.getDescripcion());
         Boton.setEnabled(true);
         if (IndiceBotones==11){
              return i+1;
          }
          IndiceBotones++;
      }
      return i;
} 
    
    int CargarFamilias(int PosInicial){
    int IndiceBotones=0;
    int i;
    Component[] componentes =jPanel1.getComponents();
    BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
    List ListaFamilias= Operaciones.ObtenerFamilias();
    if (PosInicial==ListaFamilias.size()) PosInicial=0;
   
      for  ( i=PosInicial;i<ListaFamilias.size();i++){
         Familias familias=  (Familias) ListaFamilias.get(i);
         JButton Boton;
         Boton= BotonPorNombre ("familia"+(IndiceBotones+1),jPanel1);
         Boton.setText(familias.getCodigo());
         Boton.setEnabled(true);
         if (IndiceBotones==5){
              return i+1;
          }
          IndiceBotones++;
      }
      return i;
} 
    
  void BorrarTextoBotones(JPanel Panel){
      Component[] componentes =Panel.getComponents();
        for(int i=0; i<componentes.length;i++) {
            if(componentes[i] instanceof JButton){
                JButton Boton=(JButton)componentes[i];
                Boton.setText("");
                Boton.setEnabled(false);
            }
        }   
    }
     JButton BotonPorNombre(String Nombre,JPanel Panel){
      Component[] componentes =Panel.getComponents();
        for(int i=0; i<componentes.length;i++) {
            if(componentes[i] instanceof JButton)  {
                JButton Boton=(JButton)componentes[i];
                if (Boton.getName().equals(Nombre)) {
                    return Boton;
                }
            }
        }   
        return null;
    } 
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tpvTactil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tpvTactil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tpvTactil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tpvTactil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tpvTactil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdArticulo01;
    private javax.swing.JButton cmdArticulo02;
    private javax.swing.JButton cmdArticulo03;
    private javax.swing.JButton cmdArticulo04;
    private javax.swing.JButton cmdArticulo05;
    private javax.swing.JButton cmdArticulo06;
    private javax.swing.JButton cmdArticulo07;
    private javax.swing.JButton cmdArticulo08;
    private javax.swing.JButton cmdArticulo09;
    private javax.swing.JButton cmdArticulo10;
    private javax.swing.JButton cmdArticulo11;
    private javax.swing.JButton cmdArticulo12;
    private javax.swing.JButton cmdBorrarLinea;
    private javax.swing.JButton cmdCodigoBarras;
    private javax.swing.JButton cmdFamilia1;
    private javax.swing.JButton cmdFamilia2;
    private javax.swing.JButton cmdFamilia3;
    private javax.swing.JButton cmdFamilia4;
    private javax.swing.JButton cmdFamilia5;
    private javax.swing.JButton cmdFamilia6;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
