/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidades.Articulos;
import entidades.Familias;
import java.awt.Component;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mgacosta
 */
public class tpvTactil extends javax.swing.JFrame {

    /**
     * Creates new form tpvTactil
     */
    private int Ultima=0;
    public tpvTactil() {
        initComponents();
        setLocationRelativeTo(null);
        BorrarTextoBotones(jPanel1);
        BorrarTextoBotones(jPanel2);
       Ultima= CargarFamilias(Ultima);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdFamilia1 = new javax.swing.JButton();
        cmdFamilia2 = new javax.swing.JButton();
        cmdFamilia3 = new javax.swing.JButton();
        cmdFamilia4 = new javax.swing.JButton();
        cmdFamilia5 = new javax.swing.JButton();
        cmdFamilia6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        txtDisplay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 2, 2));

        cmdFamilia1.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia1.setName("familia1"); // NOI18N
        cmdFamilia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia1);

        cmdFamilia2.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia2.setName("familia2"); // NOI18N
        cmdFamilia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia2ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia2);

        cmdFamilia3.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia3.setName("familia4"); // NOI18N
        cmdFamilia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia3ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia3);

        cmdFamilia4.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia4.setName("familia5"); // NOI18N
        cmdFamilia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia4ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia4);

        cmdFamilia5.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia5.setName("familia3"); // NOI18N
        cmdFamilia5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia5ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia5);

        cmdFamilia6.setBackground(new java.awt.Color(153, 204, 255));
        cmdFamilia6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdFamilia6.setName("familia6"); // NOI18N
        cmdFamilia6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFamilia6ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFamilia6);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new java.awt.GridLayout(3, 6, 2, 2));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("jButton7oohjo");
        jButton7.setName("articulos1"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("jButton11");
        jButton11.setName("articulos2"); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("jButton14");
        jButton14.setName("articulos3"); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("jButton9");
        jButton9.setName("articulos4"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("jButton10");
        jButton10.setName("articulos5"); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setText("jButton15");
        jButton15.setName("articulos6"); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton17.setText("jButton17");
        jButton17.setName("articulos7"); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("jButton12");
        jButton12.setName("articulos8"); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton20.setText("jButton20");
        jButton20.setName("articulos9"); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton16.setText("jButton16");
        jButton16.setName("articulos10"); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton18.setText("jButton18");
        jButton18.setName("articulos11"); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18);

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton19.setText("jButton19");
        jButton19.setName("articulos12"); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton19);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText(">>");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(new java.awt.GridLayout(8, 1));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("Salir");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton21.setText("Borrar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton21);

        jButton22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton22.setText("Codigo de Barras");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton22);

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton23.setText(">>");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));
        jPanel4.setLayout(new java.awt.GridLayout(4, 3, 2, 2));

        jButton24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton24.setText("1");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton24);

        jButton28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton28.setText("2");
        jPanel4.add(jButton28);

        jButton32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton32.setText("3");
        jPanel4.add(jButton32);

        jButton30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton30.setText("4");
        jPanel4.add(jButton30);

        jButton25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton25.setText("5");
        jPanel4.add(jButton25);

        jButton31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton31.setText("6");
        jPanel4.add(jButton31);

        jButton35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton35.setText("7");
        jPanel4.add(jButton35);

        jButton34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton34.setText("8");
        jPanel4.add(jButton34);

        jButton33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton33.setText("9");
        jPanel4.add(jButton33);

        jButton29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton29.setText("0");
        jPanel4.add(jButton29);

        jButton26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton26.setText(".");
        jPanel4.add(jButton26);

        jButton27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton27.setText("Del");
        jPanel4.add(jButton27);

        txtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDisplay))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        Articulos ObtenerPrecioArticuloPorCodigo(String Codigo){
       
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
        Articulos A;
        List ListaArticulos= Operaciones.ObtenerArticulos();
        for (int i=0;i<ListaArticulos.size();i++){
            A=(Articulos) ListaArticulos.get(i);
            if (A.getDescripcion().equals(Codigo)){
                return A;
            }
                    
        }
        return null;
        
       
    }
    
    Familias ObtenerIdFamiliaPorCodigo(String Codigo){
       
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
        Familias F;
        List ListaFamilias= Operaciones.ObtenerFamilias();
        for (int i=0;i<ListaFamilias.size();i++){
            F=(Familias) ListaFamilias.get(i);
            if (F.getCodigo().equals(Codigo)){
                return F;
            }
                    
        }
        return null;
        
       
    }
            
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        BorrarTextoBotones(jPanel1);
       Ultima= CargarFamilias(Ultima);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton24ActionPerformed

    private void cmdFamilia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia2ActionPerformed
        // TODO add your handling code here:
         BorrarTextoBotones(jPanel2);
         BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
          Familias F;
          F=Operaciones.ObtenerIdFamiliaPorCodigo(cmdFamilia2.getText());
           CargarArticulos(0,String.valueOf(F.getIdfamilias()));
        // txtDisplay.setText(String.valueOf(F.getIdfamilias()));
    }//GEN-LAST:event_cmdFamilia2ActionPerformed

    private void cmdFamilia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia1ActionPerformed
        // TODO add your handling code here:
         BorrarTextoBotones(jPanel2);
     //     BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
          Familias F;
         // F=Operaciones.ObtenerIdFamiliaPorCodigo(jButton1.getText());
         F=ObtenerIdFamiliaPorCodigo(cmdFamilia1.getText());
         CargarArticulos(0,String.valueOf(F.getIdfamilias()));
              

    }//GEN-LAST:event_cmdFamilia1ActionPerformed

    private void cmdFamilia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia3ActionPerformed
        // TODO add your handling code here:
         BorrarTextoBotones(jPanel2);
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
              Familias F;
              F=Operaciones.ObtenerIdFamiliaPorCodigo(cmdFamilia3.getText());
             
             CargarArticulos(0,String.valueOf(F.getIdfamilias()));
    }//GEN-LAST:event_cmdFamilia3ActionPerformed

    private void cmdFamilia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia4ActionPerformed
        // TODO add your handling code here:
         BorrarTextoBotones(jPanel2);
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
              Familias F;
              F=Operaciones.ObtenerIdFamiliaPorCodigo(cmdFamilia4.getText());
             
             CargarArticulos(0,String.valueOf(F.getIdfamilias()));
    }//GEN-LAST:event_cmdFamilia4ActionPerformed

    private void cmdFamilia5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia5ActionPerformed
        // TODO add your handling code here:
         BorrarTextoBotones(jPanel2);
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
              Familias F;
              F=Operaciones.ObtenerIdFamiliaPorCodigo(cmdFamilia5.getText());
             
             CargarArticulos(0,String.valueOf(F.getIdfamilias()));
    }//GEN-LAST:event_cmdFamilia5ActionPerformed

    private void cmdFamilia6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFamilia6ActionPerformed
        // TODO add your handling code here
         BorrarTextoBotones(jPanel2);
        BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
              Familias F;
              F=Operaciones.ObtenerIdFamiliaPorCodigo(cmdFamilia6.getText());
             
             CargarArticulos(0,String.valueOf(F.getIdfamilias()));
    }//GEN-LAST:event_cmdFamilia6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton7.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton7.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton11.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton11.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton14.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton14.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton9.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton9.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton10.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton10.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton15.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton15.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton17.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton17.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton12.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton12.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton20.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton20.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton16.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton16.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton18.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton18.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Articulos A=ObtenerPrecioArticuloPorCodigo(jButton19.getText());
        Object nuevo[]= {txtDisplay.getText(),jButton19.getText() ,A.getPrecio()}; //esto es por las tres columnas aunque puede variar
        temp.addRow(nuevo);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        int filaSele;
        try{
           filaSele=this.jTable1.getSelectedRow(); 
           if (filaSele==-1){
               JOptionPane.showMessageDialog(this, "Seleccione una fila ", "Grid",
                       JOptionPane.INFORMATION_MESSAGE);
           }
           else{
              ((DefaultTableModel) jTable1.getModel()).removeRow(filaSele);
           }        
        }
          catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString(), "Grid", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        
        frmCodigoBarras f = new frmCodigoBarras(this,this.jTable1);
        f.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed
 
 int CargarArticulos(int PosInicial,String IdFamilia){
    int IndiceBotones=0;
    int i;
    Component[] componentes =jPanel2.getComponents();
    BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
    List ListaArticulos;
    ListaArticulos= Operaciones.ObtenerArticulosFamilia(IdFamilia);
    if (PosInicial==ListaArticulos.size()) PosInicial=0;
      for  ( i=PosInicial;i<ListaArticulos.size();i++){
         Articulos articulo=  (Articulos) ListaArticulos.get(i);
         JButton Boton;
         Boton= BotonPorNombre ("articulos"+(IndiceBotones+1),jPanel2);
         Boton.setText(articulo.getDescripcion());
         Boton.setEnabled(true);
         if (IndiceBotones==11){
              return i+1;
          }
          IndiceBotones++;
      }
      return i;
} 
    
    int CargarFamilias(int PosInicial){
    int IndiceBotones=0;
    int i;
    Component[] componentes =jPanel1.getComponents();
    BaseDatos.Operacion Operaciones= new BaseDatos.Operacion(); 
    List ListaFamilias= Operaciones.ObtenerFamilias();
    if (PosInicial==ListaFamilias.size()) PosInicial=0;
   
      for  ( i=PosInicial;i<ListaFamilias.size();i++){
         Familias familias=  (Familias) ListaFamilias.get(i);
         JButton Boton;
         Boton= BotonPorNombre ("familia"+(IndiceBotones+1),jPanel1);
         Boton.setText(familias.getCodigo());
         Boton.setEnabled(true);
         if (IndiceBotones==5){
              return i+1;
          }
          IndiceBotones++;
      }
      return i;
} 
    
  void BorrarTextoBotones(JPanel Panel){
      Component[] componentes =Panel.getComponents();
        for(int i=0; i<componentes.length;i++) {
            if(componentes[i] instanceof JButton){
                JButton Boton=(JButton)componentes[i];
                Boton.setText("");
                Boton.setEnabled(false);
            }
        }   
    }
     JButton BotonPorNombre(String Nombre,JPanel Panel){
      Component[] componentes =Panel.getComponents();
        for(int i=0; i<componentes.length;i++) {
            if(componentes[i] instanceof JButton)  {
                JButton Boton=(JButton)componentes[i];
                if (Boton.getName().equals(Nombre)) {
                    return Boton;
                }
            }
        }   
        return null;
    } 
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tpvTactil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tpvTactil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tpvTactil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tpvTactil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tpvTactil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdFamilia1;
    private javax.swing.JButton cmdFamilia2;
    private javax.swing.JButton cmdFamilia3;
    private javax.swing.JButton cmdFamilia4;
    private javax.swing.JButton cmdFamilia5;
    private javax.swing.JButton cmdFamilia6;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
